version: '3.0'
services:
  db:
    image: postgres:9.5.22
    restart: always
    environment:
      POSTGRES_PASSWORD: yourfavpassword
    ports:
      - 5432:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data
    restart: always
